[project]
name = "personal-ai-knowledge-reinforcer"
version = "0.1.0"
description = "A local-first personal AI learning and knowledge reinforcement agent."
requires-python = ">=3.11,<3.12"

dependencies = [
    "ollama>=0.6.2",
    "llama-index",
    "chromadb",
    "llama-index-embeddings-ollama",
    "llama-index-llms-ollama",
    "docling",
    "python-multipart"
]

[tool.pytest.ini_options]
testpaths = ["tests"]